# Generated by Django 4.2.12 on 2026-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_cafeitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cafe/'),
        ),
    ]
