# Generated by Django 4.2.12 on 2026-03-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_alter_cafeitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
