# Generated by Django 4.2.12 on 2026-03-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0005_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price_per_slot', models.DecimalField(decimal_places=2, help_text='Price per 15 minutes', max_digits=6)),
                ('days_applicable', models.CharField(help_text="e.g., 'Mon-Fri', 'Sat-Sun', 'All'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cricket Pricing',
                'verbose_name_plural': 'Cricket Pricing',
                'ordering': ['start_time'],
            },
        ),
    ]
