# Generated by Django 4.2.12 on 2026-03-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0007_cafeorder_cafeorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Main contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Main contact email', max_length=254)),
                ('address', models.TextField(help_text='Physical address')),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number', max_length=20, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel URL', null=True)),
                ('google_maps_url', models.URLField(blank=True, help_text='Google Maps location URL', null=True)),
                ('working_hours', models.CharField(default='10AM - 10PM Daily', help_text='Business working hours', max_length=200)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'ordering': ['key'], 'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
