# Generated by Django 4.2.12 on 2026-04-01 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0009_payment_packagecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('duration', models.CharField(choices=[('3_months', '3 Months'), ('6_months', '6 Months')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(default=10)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('card_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('qr_code_url', models.URLField(blank=True, max_length=500, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='membership_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Card',
                'verbose_name_plural': 'Membership Cards',
                'db_table': 'arena_membership_cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
