# Generated by Django 4.2.12 on 2026-04-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0010_membershipcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_orders', to='arena.payment'),
        ),
        migrations.AddField(
            model_name='cafeorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Pay Online'), ('delivery', 'Pay on Delivery')], max_length=20, null=True),
        ),
    ]
