# Generated by Django 4.2.12 on 2026-04-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0011_cafeorder_payment_cafeorder_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeorder',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='cafeorder',
            name='payment_method',
        ),
    ]
